---
labels:
  players: "Players"
  sysadmin: "System Administrator"
email:
  header-crlf: "\r\n"
  header-mime: "text/plain; charset=iso-8859-1"
  subject:
    prefix: "PocketMine - "
    cmd-send: "'%s' has sent you a message"
    event-start: "Start - %s"
    event-stop: "Stop - %s" 
    event-auth: "%s joined '%s'"
    event-quit: "%s left '%s'" 
  body:
    greeting: "Hello %s,\n\n"
    signature: "\n\nFrom,\n%s\n\n--Sent from '%s'"
    players-hdr: "\n\nOnline Players:\n\n"
    players-row: " * %s -> %s\n"
    event-start: "Server started. Enjoy the game!\n\nDate: %s\n\nServer: %s\n\nVersion: %s"
    event-stop: "Server stopped. Game play will resume shortly.\nYou will receive a message when the server is available.\n\nDate: %s\n\nServer: %s\n\nVersion: %s" 
    event-auth: "%s joined the game.\n\nDate: %s\n\nServer: %s\n\nWorld: %s"
    event-quit: "%s left the game.\n\nDate: %s\n\nServer: %s\n\nWorld: %s"
    cmd-send: "%s"
commands:
  msg-add-success: "%s added to buddy list"
  msg-add-error: "%s is already a buddy"
  msg-del-success: "%s removed from buddy list"
  msg-del-error: "%s is not a buddy"
  msg-list-email-label: "Address: "
  msg-list-email-unset: "Empty - use '/email reg <email>' command"
  msg-list-buddy-label: "Buddies: "
  msg-list-buddy-unset: "Empty - use '/email add <player>' command"
  msg-reg-success: "Email address added"
  msg-reg-error: "Invalid email address"
  msg-unreg-success: "Email address removed"
  msg-send-success: "Your email was sent"
  msg-send-general-error: "Unable to send. Contact the Admin."
  msg-player-not-registered: "No email address for '%s'"
console:
  msg-all-notifications-off: "Unable to send. Check the master switch in the 'config.cfg'"
  msg_player_no_buddies: "%s has no buddies"
  msg-player-not-registered: "Unable to send. The player, %s, has not registered an email address."
  msg-send-error: "Unable to send. Check the 'sendmail_path' property in 'php.ini' is correct."
  msg-send-success: "Your email was sent"    
  msg-sysadmin-email-notset1: "System alerts disabled. System operator email address not set in 'config.xml'."
  msg-sysadmin-email-notset2: "Unable to send. System operator email address not set in 'config.xml'."
  msg-no-registered-emails: "Unable to send. There are no registered email addresses."
usage:
  header: "---Showing email sub-command help page"
  player:
    cmd-add: "Add buddy to your alerts"
    cmd-del: "Remove buddy from your alerts"
    cmd-list: "Show your email and buddy configuration"
    cmd-send: "Send a player an email"
    cmd-reg: "Register your email to receive alerts"
    cmd-unreg: "Unregister your email from receiving alerts"
    cmd-unsub: "Unsubscribe from a buddy's alerts"
  console:
    cmd-add: "Add buddy to player's alerts"
    cmd-del: "Remove buddy from player's alerts"
    cmd-list: "Show player's email and buddy configuration"
    cmd-send: "Send a player or everyone an email"
    cmd-reg: "Register player's email to receive alerts"
    cmd-unreg: "Unregister player's email from receiving alerts"
    cmd-unsub: "Unsubscribe player from another player's alerts"
...